apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseProxy
  name: reverseProxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseProxy
    spec:
      containers:
      - image: shahjuhi1108/udagram-reverseProxy-image1:latest
        name: reverseProxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always